workflows:
  release-android:
    name: Release Android Build
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.example.news"
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build apk --release
      - name: Dekodiranje keystore-a
        script: |
         echo $CM_KEYSTORE | base64 --decode > android/my-release-key.jks
      - name: Build Shorebird release
        script: |
          shorebird release android
      - name: Patch Shorebird
        script: |
          shorebird patch android
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
