name: news
description: "Flutter app for news."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  email_validator: ^3.0.0
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  
  

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/news.png" 
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - lib/l10n/en.json
    - lib/l10n/hr.json
    - assets/news.png
    - shorebird.yaml
  